name: Swift
on:
  push:
    branches: [ '*' ]
  #workflow_dispatch:
  pull_request:

jobs:
  android:
    name: Android
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'macos-15-intel']
        swift: ['nightly-6.3']
        arch: ['x86_64']
        sdk: ['28', '29', '31', '33']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      #- uses: skiptools/actions/setup-skip@v1
      - uses: skiptools/actions/setup-skip@emulator-testing
        with:
          swift-version: ${{ matrix.swift }}
          install-swift-android-sdk: true
          swift-android-sdk-version: ${{ matrix.swift }}
          gradle-version: 'none'
      - name: "Build Swift Package for Android"
        run: |
          ANDROID_NDK_ROOT="" ANDROID_SDK_VERSION=${{ matrix.sdk }} skip android build --arch ${{ matrix.arch }} --android-api-level ${{ matrix.sdk }}
      - name: "Create Android emulator"
        run: |
          skip android emulator create --android-api-level ${{ matrix.sdk }}
      - name: "Launch emulator"
        run: |
          skip android emulator launch --background
      - name: "Test Swift package on emulator"
        run: |
          skip android test --apk

